import { Subject } from '@/types/app';

export const subjects: Subject[] = [
  // Year 1 Semester 1
  { id: 'cse1101', code: 'CSE 1101', name: 'Introduction to Computer Science', credits: 3, year: 1, semester: 1, type: 'theory', difficulty: 'beginner', description: 'Foundations of computing, number systems, basic hardware/software concepts, and introduction to programming logic.', whatYouLearn: ['Number systems & binary arithmetic', 'Computer organization basics', 'Introduction to algorithms', 'Problem-solving techniques'], youtubeQuery: 'introduction+to+computer+science+bangla', gfgQuery: 'introduction-to-computer-science' },
  { id: 'math1101', code: 'MATH 1101', name: 'Differential Calculus & Coordinate Geometry', credits: 3, year: 1, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Limits, continuity, differentiation, applications of derivatives, and 2D/3D coordinate geometry.', whatYouLearn: ['Limits & continuity', 'Differentiation rules', 'Applications of derivatives', 'Coordinate geometry in 2D/3D'], youtubeQuery: 'differential+calculus+bangla+tutorial', gfgQuery: 'differential-calculus' },
  { id: 'phy1101', code: 'PHY 1101', name: 'Physics I', credits: 3, year: 1, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Mechanics, waves, oscillations, thermodynamics, and physical optics.', whatYouLearn: ['Newtonian mechanics', 'Wave motion & oscillations', 'Thermodynamics laws', 'Physical optics'], youtubeQuery: 'physics+1+bangla+lecture', gfgQuery: 'physics-mechanics' },
  { id: 'eng1101', code: 'ENG 1101', name: 'Communicative English', credits: 3, year: 1, semester: 1, type: 'theory', difficulty: 'beginner', description: 'English language skills for academic and professional communication.', whatYouLearn: ['Academic writing', 'Presentation skills', 'Grammar & vocabulary', 'Professional communication'], youtubeQuery: 'communicative+english+bangla', gfgQuery: 'english-communication-skills' },
  { id: 'stat1101', code: 'STAT 1101', name: 'Introduction to Statistics', credits: 3, year: 1, semester: 1, type: 'theory', difficulty: 'beginner', description: 'Descriptive statistics, probability basics, distributions, and data representation.', whatYouLearn: ['Measures of central tendency', 'Probability fundamentals', 'Data visualization', 'Statistical distributions'], youtubeQuery: 'statistics+bangla+tutorial', gfgQuery: 'statistics' },
  { id: 'cse1102', code: 'CSE 1102', name: 'Computer Science Lab', credits: 1.5, year: 1, semester: 1, type: 'lab', difficulty: 'beginner', description: 'Hands-on lab for computer science fundamentals, hardware identification, and basic software tools.', whatYouLearn: ['Hardware components', 'Operating system basics', 'Office tools proficiency', 'Basic troubleshooting'], youtubeQuery: 'computer+science+lab+bangla', gfgQuery: 'computer-science-lab' },
  { id: 'phy1102', code: 'PHY 1102', name: 'Physics Lab', credits: 1.5, year: 1, semester: 1, type: 'lab', difficulty: 'beginner', description: 'Laboratory experiments in mechanics, optics, and wave motion.', whatYouLearn: ['Measurement techniques', 'Experimental methods', 'Data analysis', 'Lab report writing'], youtubeQuery: 'physics+lab+experiments+bangla', gfgQuery: 'physics-lab' },

  // Year 1 Semester 2
  { id: 'cse1201', code: 'CSE 1201', name: 'Structured Programming in C', credits: 3, year: 1, semester: 2, type: 'theory', difficulty: 'beginner', description: 'C programming fundamentals — variables, loops, arrays, functions, pointers, file handling.', whatYouLearn: ['Variables, data types, operators', 'Control structures & loops', 'Functions & recursion', 'Pointers & memory management'], youtubeQuery: 'c+programming+bangla+tutorial', gfgQuery: 'c-programming-language' },
  { id: 'math1201', code: 'MATH 1201', name: 'Integral Calculus & Differential Equations', credits: 3, year: 1, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Integration techniques, definite integrals, and ordinary differential equations.', whatYouLearn: ['Integration techniques', 'Definite & improper integrals', 'First-order ODEs', 'Higher-order ODEs'], youtubeQuery: 'integral+calculus+differential+equations+bangla', gfgQuery: 'integral-calculus' },
  { id: 'phy1201', code: 'PHY 1201', name: 'Physics II', credits: 3, year: 1, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Electricity, magnetism, electromagnetic waves, and modern physics.', whatYouLearn: ['Electrostatics & magnetism', 'Electromagnetic induction', 'AC/DC circuits', 'Modern physics basics'], youtubeQuery: 'physics+2+electricity+magnetism+bangla', gfgQuery: 'physics-electricity-magnetism' },
  { id: 'chem1201', code: 'CHEM 1201', name: 'Chemistry', credits: 3, year: 1, semester: 2, type: 'theory', difficulty: 'beginner', description: 'General chemistry including organic, inorganic, and physical chemistry fundamentals.', whatYouLearn: ['Atomic structure & bonding', 'Organic chemistry basics', 'Chemical equilibrium', 'Electrochemistry'], youtubeQuery: 'chemistry+bangla+tutorial', gfgQuery: 'chemistry' },
  { id: 'eng1202', code: 'ENG 1202', name: 'Technical Writing & Presentation', credits: 3, year: 1, semester: 2, type: 'theory', difficulty: 'beginner', description: 'Technical report writing, research papers, and professional presentation skills.', whatYouLearn: ['Technical report format', 'Research paper writing', 'Presentation techniques', 'Professional emails'], youtubeQuery: 'technical+writing+bangla', gfgQuery: 'technical-writing' },
  { id: 'cse1202', code: 'CSE 1202', name: 'C Programming Lab', credits: 1.5, year: 1, semester: 2, type: 'lab', difficulty: 'beginner', description: 'Practical C programming exercises — implementing algorithms, data manipulation, file I/O.', whatYouLearn: ['Coding practice in C', 'Algorithm implementation', 'Debugging techniques', 'File handling in C'], youtubeQuery: 'c+programming+lab+bangla', gfgQuery: 'c-programming-lab' },
  { id: 'chem1202', code: 'CHEM 1202', name: 'Chemistry Lab', credits: 1.5, year: 1, semester: 2, type: 'lab', difficulty: 'beginner', description: 'Chemistry laboratory experiments and analysis techniques.', whatYouLearn: ['Lab safety procedures', 'Chemical analysis', 'Titration techniques', 'Lab report writing'], youtubeQuery: 'chemistry+lab+bangla', gfgQuery: 'chemistry-lab' },

  // Year 2 Semester 1
  { id: 'cse2101', code: 'CSE 2101', name: 'Object Oriented Programming in Java', credits: 3, year: 2, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'OOP concepts — classes, objects, inheritance, polymorphism, encapsulation using Java.', whatYouLearn: ['Classes & objects', 'Inheritance & polymorphism', 'Interfaces & abstract classes', 'Exception handling & collections'], youtubeQuery: 'java+oop+bangla+tutorial', gfgQuery: 'java' },
  { id: 'cse2103', code: 'CSE 2103', name: 'Data Structures', credits: 3, year: 2, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Arrays, linked lists, stacks, queues, trees, graphs, hashing, and sorting algorithms.', whatYouLearn: ['Arrays & linked lists', 'Stacks & queues', 'Trees & binary search trees', 'Graphs & hashing'], youtubeQuery: 'data+structures+bangla+tutorial', gfgQuery: 'data-structures' },
  { id: 'math2101', code: 'MATH 2101', name: 'Linear Algebra & Matrix Theory', credits: 3, year: 2, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Matrices, determinants, vector spaces, eigenvalues, and linear transformations.', whatYouLearn: ['Matrix operations', 'Vector spaces', 'Eigenvalues & eigenvectors', 'Linear transformations'], youtubeQuery: 'linear+algebra+bangla+tutorial', gfgQuery: 'linear-algebra' },
  { id: 'math2103', code: 'MATH 2103', name: 'Complex Variables & Fourier Series', credits: 3, year: 2, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Complex analysis, analytic functions, contour integration, and Fourier series.', whatYouLearn: ['Complex numbers & functions', 'Analytic functions', 'Contour integration', 'Fourier series & transforms'], youtubeQuery: 'complex+variables+fourier+series+bangla', gfgQuery: 'complex-analysis' },
  { id: 'eee2101', code: 'EEE 2101', name: 'Basic Electronics', credits: 3, year: 2, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Semiconductor devices, diodes, transistors, op-amps, and basic circuit design.', whatYouLearn: ['Semiconductor physics', 'Diodes & transistors', 'Op-amp circuits', 'Digital electronics basics'], youtubeQuery: 'basic+electronics+bangla+tutorial', gfgQuery: 'basic-electronics' },
  { id: 'cse2102', code: 'CSE 2102', name: 'OOP Lab', credits: 1.5, year: 2, semester: 1, type: 'lab', difficulty: 'intermediate', description: 'Java programming lab for OOP concepts implementation.', whatYouLearn: ['Java coding practice', 'OOP implementation', 'GUI applications', 'Project development'], youtubeQuery: 'java+oop+lab+bangla', gfgQuery: 'java-programming-lab' },
  { id: 'cse2104', code: 'CSE 2104', name: 'Data Structures Lab', credits: 1.5, year: 2, semester: 1, type: 'lab', difficulty: 'intermediate', description: 'Implementation of data structures and algorithms in C/C++.', whatYouLearn: ['DSA implementation', 'Algorithm coding', 'Time complexity analysis', 'Problem solving'], youtubeQuery: 'data+structures+lab+bangla', gfgQuery: 'data-structures-lab' },

  // Year 2 Semester 2
  { id: 'cse2201', code: 'CSE 2201', name: 'Algorithms Design & Analysis', credits: 3, year: 2, semester: 2, type: 'theory', difficulty: 'advanced', description: 'Algorithm design paradigms — divide & conquer, greedy, dynamic programming, graph algorithms.', whatYouLearn: ['Divide & conquer', 'Greedy algorithms', 'Dynamic programming', 'Graph algorithms & NP-completeness'], youtubeQuery: 'algorithms+design+analysis+bangla', gfgQuery: 'fundamentals-of-algorithms' },
  { id: 'cse2203', code: 'CSE 2203', name: 'Digital Logic Design', credits: 3, year: 2, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Boolean algebra, logic gates, combinational & sequential circuits, flip-flops, counters.', whatYouLearn: ['Boolean algebra & gates', 'Combinational circuits', 'Sequential circuits', 'Flip-flops & counters'], youtubeQuery: 'digital+logic+design+bangla', gfgQuery: 'digital-logic-design' },
  { id: 'math2201', code: 'MATH 2201', name: 'Probability & Statistics', credits: 3, year: 2, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Probability theory, distributions, hypothesis testing, regression analysis.', whatYouLearn: ['Probability theory', 'Random variables & distributions', 'Hypothesis testing', 'Regression analysis'], youtubeQuery: 'probability+statistics+bangla+tutorial', gfgQuery: 'probability-and-statistics' },
  { id: 'eee2201', code: 'EEE 2201', name: 'Basic Electrical Engineering', credits: 3, year: 2, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'AC/DC circuits, electrical machines, power systems, and network analysis.', whatYouLearn: ['Circuit analysis', 'AC/DC fundamentals', 'Electrical machines', 'Power systems basics'], youtubeQuery: 'electrical+engineering+bangla', gfgQuery: 'basic-electrical-engineering' },
  { id: 'cse2205', code: 'CSE 2205', name: 'Discrete Mathematics', credits: 3, year: 2, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Sets, relations, functions, graph theory, combinatorics, and mathematical logic.', whatYouLearn: ['Set theory & logic', 'Relations & functions', 'Graph theory', 'Combinatorics'], youtubeQuery: 'discrete+mathematics+bangla+tutorial', gfgQuery: 'discrete-mathematics' },
  { id: 'cse2202', code: 'CSE 2202', name: 'Algorithms Lab', credits: 1.5, year: 2, semester: 2, type: 'lab', difficulty: 'advanced', description: 'Implementation of algorithm design paradigms and complexity analysis.', whatYouLearn: ['Algorithm implementation', 'Complexity measurement', 'Optimization techniques', 'Competitive programming intro'], youtubeQuery: 'algorithms+lab+bangla', gfgQuery: 'algorithms-lab' },
  { id: 'cse2204', code: 'CSE 2204', name: 'Digital Logic Design Lab', credits: 1.5, year: 2, semester: 2, type: 'lab', difficulty: 'intermediate', description: 'Hardware implementation of digital circuits using logic gates and ICs.', whatYouLearn: ['Circuit building', 'IC usage', 'Logic analyzer', 'Circuit debugging'], youtubeQuery: 'digital+logic+lab+bangla', gfgQuery: 'digital-logic-lab' },

  // Year 3 Semester 1
  { id: 'cse3101', code: 'CSE 3101', name: 'Computer Architecture & Organization', credits: 3, year: 3, semester: 1, type: 'theory', difficulty: 'advanced', description: 'CPU design, instruction sets, pipelining, memory hierarchy, and I/O systems.', whatYouLearn: ['CPU architecture & design', 'Instruction set architecture', 'Pipelining techniques', 'Cache & memory hierarchy'], youtubeQuery: 'computer+architecture+organization+bangla', gfgQuery: 'computer-organization-and-architecture-tutorials' },
  { id: 'cse3103', code: 'CSE 3103', name: 'Operating Systems', credits: 3, year: 3, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Process management, memory management, file systems, I/O, and concurrency.', whatYouLearn: ['Process scheduling', 'Memory management', 'File systems', 'Deadlocks & synchronization'], youtubeQuery: 'operating+system+bangla+lecture', gfgQuery: 'operating-systems' },
  { id: 'cse3105', code: 'CSE 3105', name: 'Database Management Systems', credits: 3, year: 3, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Relational model, SQL, normalization, transactions, indexing, and NoSQL basics.', whatYouLearn: ['Relational model & SQL', 'Normalization (1NF-BCNF)', 'Transaction management', 'Indexing & query optimization'], youtubeQuery: 'dbms+sql+bangla+tutorial', gfgQuery: 'dbms' },
  { id: 'cse3107', code: 'CSE 3107', name: 'Theory of Computation', credits: 3, year: 3, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Automata theory, regular languages, context-free grammars, Turing machines.', whatYouLearn: ['Finite automata', 'Regular expressions', 'Context-free grammars', 'Turing machines & decidability'], youtubeQuery: 'theory+of+computation+bangla', gfgQuery: 'theory-of-computation-automata-tutorials' },
  { id: 'cse3109', code: 'CSE 3109', name: 'Computer Graphics', credits: 3, year: 3, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'Graphics rendering, transformations, clipping, 3D modeling, and animation.', whatYouLearn: ['2D/3D transformations', 'Rasterization algorithms', 'Lighting & shading', 'OpenGL basics'], youtubeQuery: 'computer+graphics+bangla+tutorial', gfgQuery: 'computer-graphics-2' },
  { id: 'cse3102', code: 'CSE 3102', name: 'OS Lab', credits: 1.5, year: 3, semester: 1, type: 'lab', difficulty: 'advanced', description: 'Linux commands, shell scripting, process management, and system calls.', whatYouLearn: ['Linux terminal mastery', 'Shell scripting', 'Process management', 'System call programming'], youtubeQuery: 'operating+system+lab+linux+bangla', gfgQuery: 'operating-system-lab' },
  { id: 'cse3106', code: 'CSE 3106', name: 'DBMS Lab', credits: 1.5, year: 3, semester: 1, type: 'lab', difficulty: 'intermediate', description: 'SQL queries, database design, normalization exercises, and DBMS project.', whatYouLearn: ['SQL queries mastery', 'Database design', 'Stored procedures', 'Full DBMS project'], youtubeQuery: 'dbms+sql+lab+bangla', gfgQuery: 'dbms-lab' },

  // Year 3 Semester 2
  { id: 'cse3201', code: 'CSE 3201', name: 'Computer Networks', credits: 3, year: 3, semester: 2, type: 'theory', difficulty: 'advanced', description: 'OSI/TCP-IP models, routing, switching, protocols, and network security.', whatYouLearn: ['OSI & TCP/IP models', 'Routing algorithms', 'Transport layer protocols', 'Network security basics'], youtubeQuery: 'computer+networks+bangla+lecture', gfgQuery: 'computer-network-tutorials' },
  { id: 'cse3203', code: 'CSE 3203', name: 'Software Engineering & SDLC', credits: 3, year: 3, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Software development lifecycle, agile, testing, project management, and quality assurance.', whatYouLearn: ['SDLC models (Agile, Waterfall)', 'Requirements engineering', 'Software testing', 'Project management'], youtubeQuery: 'software+engineering+sdlc+bangla', gfgQuery: 'software-engineering' },
  { id: 'cse3205', code: 'CSE 3205', name: 'Compiler Design', credits: 3, year: 3, semester: 2, type: 'theory', difficulty: 'advanced', description: 'Lexical analysis, parsing, syntax-directed translation, code generation, and optimization.', whatYouLearn: ['Lexical analysis', 'Parsing techniques', 'Semantic analysis', 'Code generation & optimization'], youtubeQuery: 'compiler+design+bangla+tutorial', gfgQuery: 'compiler-design-tutorials' },
  { id: 'cse3207', code: 'CSE 3207', name: 'Microprocessors & Assembly Language', credits: 3, year: 3, semester: 2, type: 'theory', difficulty: 'advanced', description: '8086 architecture, assembly language programming, interrupts, and I/O interfacing.', whatYouLearn: ['8086 architecture', 'Assembly language', 'Interrupt handling', 'I/O interfacing'], youtubeQuery: 'microprocessor+assembly+language+bangla', gfgQuery: 'microprocessor-tutorials' },
  { id: 'cse3209', code: 'CSE 3209', name: 'Numerical Methods', credits: 3, year: 3, semester: 2, type: 'theory', difficulty: 'intermediate', description: 'Numerical solutions of equations, interpolation, integration, and differential equations.', whatYouLearn: ['Root finding methods', 'Interpolation', 'Numerical integration', 'ODE solutions'], youtubeQuery: 'numerical+methods+bangla+tutorial', gfgQuery: 'numerical-methods' },
  { id: 'cse3202', code: 'CSE 3202', name: 'Networks Lab', credits: 1.5, year: 3, semester: 2, type: 'lab', difficulty: 'advanced', description: 'Network configuration, packet analysis with Wireshark, and socket programming.', whatYouLearn: ['Network configuration', 'Wireshark analysis', 'Socket programming', 'Network troubleshooting'], youtubeQuery: 'computer+networks+lab+bangla', gfgQuery: 'networks-lab' },
  { id: 'cse3208', code: 'CSE 3208', name: 'Microprocessors Lab', credits: 1.5, year: 3, semester: 2, type: 'lab', difficulty: 'advanced', description: 'Assembly language programming and microprocessor interfacing experiments.', whatYouLearn: ['Assembly coding', 'Hardware interfacing', 'Interrupt programming', 'I/O device control'], youtubeQuery: 'microprocessor+lab+bangla', gfgQuery: 'microprocessor-lab' },

  // Year 4 Semester 1
  { id: 'cse4101', code: 'CSE 4101', name: 'Artificial Intelligence', credits: 3, year: 4, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Search algorithms, knowledge representation, expert systems, NLP, and game theory.', whatYouLearn: ['Search algorithms (BFS, DFS, A*)', 'Knowledge representation', 'Expert systems', 'NLP & game theory'], youtubeQuery: 'artificial+intelligence+bangla+tutorial', gfgQuery: 'artificial-intelligence' },
  { id: 'cse4103', code: 'CSE 4103', name: 'Machine Learning', credits: 3, year: 4, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Supervised/unsupervised learning, neural networks, SVM, decision trees, deep learning basics.', whatYouLearn: ['Supervised learning algorithms', 'Neural networks & deep learning', 'Clustering & dimensionality reduction', 'Model evaluation & tuning'], youtubeQuery: 'machine+learning+python+bangla+tutorial', gfgQuery: 'machine-learning' },
  { id: 'cse4105', code: 'CSE 4105', name: 'Information Security & Cryptography', credits: 3, year: 4, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Encryption, authentication, digital signatures, network security protocols.', whatYouLearn: ['Symmetric & asymmetric encryption', 'Digital signatures', 'Network security protocols', 'Security best practices'], youtubeQuery: 'information+security+cryptography+bangla', gfgQuery: 'cryptography' },
  { id: 'cse4107', code: 'CSE 4107', name: 'Web Technologies & Frameworks', credits: 3, year: 4, semester: 1, type: 'theory', difficulty: 'intermediate', description: 'HTML5, CSS3, JavaScript, React/Angular, Node.js, REST APIs, and web security.', whatYouLearn: ['HTML5, CSS3, JavaScript ES6+', 'Frontend frameworks (React)', 'Backend (Node.js, Express)', 'REST APIs & databases'], youtubeQuery: 'web+development+bangla+2024', gfgQuery: 'web-technology' },
  { id: 'cse4109', code: 'CSE 4109', name: 'Elective I', credits: 3, year: 4, semester: 1, type: 'theory', difficulty: 'advanced', description: 'Elective course chosen from department offerings like IoT, Image Processing, Bioinformatics.', whatYouLearn: ['Specialized topic depth', 'Research methodology', 'Advanced applications', 'Seminar presentations'], youtubeQuery: 'cse+elective+courses+bangla', gfgQuery: 'elective-subjects' },
  { id: 'cse4102', code: 'CSE 4102', name: 'AI & ML Lab', credits: 1.5, year: 4, semester: 1, type: 'lab', difficulty: 'advanced', description: 'Practical AI and ML implementations using Python, scikit-learn, TensorFlow.', whatYouLearn: ['Python ML libraries', 'Model training & evaluation', 'Deep learning basics', 'AI project development'], youtubeQuery: 'ai+ml+lab+python+bangla', gfgQuery: 'machine-learning-lab' },
  { id: 'cse4108', code: 'CSE 4108', name: 'Web Technologies Lab', credits: 1.5, year: 4, semester: 1, type: 'lab', difficulty: 'intermediate', description: 'Full-stack web development project using modern frameworks.', whatYouLearn: ['Full-stack project', 'Frontend + backend', 'Database integration', 'Deployment'], youtubeQuery: 'web+development+lab+bangla', gfgQuery: 'web-development-lab' },

  // Year 4 Semester 2
  { id: 'cse4201', code: 'CSE 4201', name: 'Project / Thesis', credits: 6, year: 4, semester: 2, type: 'project', difficulty: 'advanced', description: 'Final year project or research thesis under faculty supervision.', whatYouLearn: ['Research methodology', 'Project management', 'Technical writing', 'Presentation skills'], youtubeQuery: 'final+year+project+thesis+cse+bangla', gfgQuery: 'final-year-project-ideas' },
  { id: 'cse4203', code: 'CSE 4203', name: 'Distributed Systems', credits: 3, year: 4, semester: 2, type: 'theory', difficulty: 'advanced', description: 'Distributed computing models, consistency, replication, fault tolerance, and distributed databases.', whatYouLearn: ['Distributed architectures', 'Consistency models', 'Fault tolerance', 'Distributed databases'], youtubeQuery: 'distributed+systems+bangla+tutorial', gfgQuery: 'distributed-systems' },
  { id: 'cse4205', code: 'CSE 4205', name: 'Cloud Computing & DevOps', credits: 3, year: 4, semester: 2, type: 'theory', difficulty: 'advanced', description: 'Cloud service models, virtualization, containers, CI/CD, and cloud security.', whatYouLearn: ['Cloud models (IaaS, PaaS, SaaS)', 'Docker & Kubernetes', 'CI/CD pipelines', 'Cloud security'], youtubeQuery: 'cloud+computing+devops+bangla', gfgQuery: 'cloud-computing' },
  { id: 'cse4207', code: 'CSE 4207', name: 'Professional Ethics & Cyber Law', credits: 3, year: 4, semester: 2, type: 'theory', difficulty: 'beginner', description: 'Professional ethics, intellectual property, cybercrime laws, and digital rights.', whatYouLearn: ['Professional ethics in IT', 'Intellectual property rights', 'Cybercrime & cyber law', 'Digital privacy & rights'], youtubeQuery: 'professional+ethics+cyber+law+bangla', gfgQuery: 'cyber-laws' },
  { id: 'cse4209', code: 'CSE 4209', name: 'Elective II', credits: 3, year: 4, semester: 2, type: 'theory', difficulty: 'advanced', description: 'Second elective from advanced topics like Robotics, Data Mining, NLP.', whatYouLearn: ['Advanced specialization', 'Research exposure', 'Industry applications', 'Seminar & presentation'], youtubeQuery: 'cse+advanced+elective+bangla', gfgQuery: 'elective-courses' },
  { id: 'cse4202', code: 'CSE 4202', name: 'Project Lab', credits: 3, year: 4, semester: 2, type: 'lab', difficulty: 'advanced', description: 'Dedicated lab sessions for final year project development and thesis work.', whatYouLearn: ['Project implementation', 'Testing & debugging', 'Documentation', 'Demo & presentation'], youtubeQuery: 'final+year+project+lab+bangla', gfgQuery: 'project-lab' },
];

export const semesterLabels: Record<string, string> = {
  '1-1': 'Year 1, Semester 1',
  '1-2': 'Year 1, Semester 2',
  '2-1': 'Year 2, Semester 1',
  '2-2': 'Year 2, Semester 2',
  '3-1': 'Year 3, Semester 1',
  '3-2': 'Year 3, Semester 2',
  '4-1': 'Year 4, Semester 1',
  '4-2': 'Year 4, Semester 2',
};
