import { Platform } from '@/types/app';

export const platforms: Platform[] = [
  { id: 'w3schools', name: 'W3Schools', url: 'https://www.w3schools.com', tagline: 'The world\'s largest web developer site', description: 'W3Schools is the ultimate quick reference for web technologies. It covers HTML, CSS, JavaScript, Python, SQL, and more with interactive "Try it Yourself" editors.', difficulty: 'Beginner', bestFor: ['HTML/CSS syntax', 'JavaScript basics', 'SQL queries', 'Python intro', 'Quick reference'], features: ['Interactive code editor', 'Free tutorials for 30+ languages', 'Certification exams', 'Exercises & quizzes'], tips: ['Use for quick syntax lookup, not deep learning', 'Do all exercises in each tutorial', 'Use "Try it Yourself" for every concept', 'The SQL tutorial is excellent for DBMS prep'], color: 'from-green-500 to-green-600' },
  { id: 'hackerrank', name: 'HackerRank', url: 'https://www.hackerrank.com', tagline: 'Practice coding & get certified', description: 'HackerRank offers coding challenges across domains and provides skill verification certificates that employers recognize.', difficulty: 'Beginner-Intermediate', bestFor: ['Interview prep', 'Skill certificates', 'Python/Java/SQL practice', 'Problem solving'], features: ['Skill-based challenges', 'Company-specific prep', 'Free certificates', 'Contest participation'], tips: ['Complete Python Basic and SQL Basic certificates first', 'These certificates add value to your resume', 'Practice the 30 Days of Code challenge', 'Use for interview preparation'], color: 'from-green-600 to-emerald-600' },
  { id: 'leetcode', name: 'LeetCode', url: 'https://leetcode.com', tagline: 'The #1 platform for interview prep', description: 'LeetCode is the gold standard for technical interview preparation with 2000+ problems organized by company and topic.', difficulty: 'Intermediate-Advanced', bestFor: ['FAANG interview prep', 'DSA mastery', 'Company-specific problems', 'Contest rating'], features: ['Company-tagged problems', 'Discussion forum', 'Weekly contests', 'Premium company questions'], tips: ['Start with Easy, move to Medium after 50 Easy problems', 'Do 2-3 problems daily consistently', 'Study patterns (sliding window, two pointers, etc.)', 'Read discussion solutions after attempting'], color: 'from-yellow-500 to-orange-500' },
  { id: 'codeforces', name: 'Codeforces', url: 'https://codeforces.com', tagline: 'Competitive programming platform #1', description: 'Codeforces hosts regular programming contests with a global rating system. It\'s the most popular competitive programming platform.', difficulty: 'Intermediate-Advanced', bestFor: ['Competitive programming', 'Algorithm practice', 'Contest participation', 'Global ranking'], features: ['Regular contests (Div 1-4)', 'Problem archive', 'Rating system', 'Editorial solutions'], tips: ['Start with Div.3 A and B problems', 'Read editorials after every contest', 'Join virtual contests for practice', 'Aim for Specialist (1400+) rating first'], color: 'from-blue-600 to-blue-700' },
  { id: 'gfg', name: 'GeeksforGeeks', url: 'https://www.geeksforgeeks.org', tagline: 'A computer science portal for geeks', description: 'GFG has comprehensive articles on every CS topic, making it perfect for HSTU exam preparation and interview prep.', difficulty: 'All Levels', bestFor: ['CS theory', 'HSTU exam prep', 'Interview questions', 'DSA practice'], features: ['Topic-wise articles', 'Practice problems', 'Interview experiences', 'Course material'], tips: ['Use for every HSTU subject — they have detailed articles', 'The DSA practice section is excellent', 'Read company interview experiences before applying', 'SDE Sheet is a must for job prep'], color: 'from-green-600 to-green-700' },
  { id: 'freecodecamp', name: 'freeCodeCamp', url: 'https://www.freecodecamp.org', tagline: 'Learn to code for free', description: 'freeCodeCamp provides completely free, project-based certifications in web development, data analysis, and more.', difficulty: 'Beginner', bestFor: ['Web development', 'Free certifications', 'Project-based learning', 'Portfolio building'], features: ['300+ hours of free content', 'Industry-recognized certificates', 'Project-based curriculum', 'Supportive community'], tips: ['Complete Responsive Web Design certification first', 'The JS Algorithms certification is excellent for interviews', 'Build all 5 projects for each certification', 'Add certificates to LinkedIn'], color: 'from-purple-600 to-purple-700' },
  { id: 'coursera', name: 'Coursera', url: 'https://www.coursera.org', tagline: 'University-level courses from top institutions', description: 'Coursera partners with universities and companies to provide professional courses. Financial aid is available for free access.', difficulty: 'All Levels', bestFor: ['University courses', 'Professional certificates', 'Google/Meta certs', 'Deep learning'], features: ['University partnerships', 'Financial aid available', 'Professional certificates', 'Degree programs'], tips: ['Apply for Financial Aid to get any course free', 'Google Data Analytics certificate is highly valued', 'Meta Front-End Developer is great for web devs', 'Andrew Ng\'s ML course is legendary'], color: 'from-blue-500 to-indigo-600' },
  { id: 'kaggle', name: 'Kaggle', url: 'https://www.kaggle.com', tagline: 'Your home for data science & ML', description: 'Kaggle offers free ML courses, competitions, datasets, and GPU-powered notebooks for hands-on machine learning.', difficulty: 'Intermediate', bestFor: ['Data Science', 'ML competitions', 'Free GPU notebooks', 'Portfolio datasets'], features: ['Free GPU/TPU notebooks', 'ML competitions', 'Kaggle Learn courses', 'Public datasets'], tips: ['Complete Intro to ML and Intermediate ML courses first', 'Join beginner-friendly competitions (Titanic, House Prices)', 'Use Kaggle notebooks for your portfolio', 'The community is very helpful'], color: 'from-cyan-500 to-blue-500' },
  { id: 'cs50', name: 'CS50 Harvard', url: 'https://cs50.harvard.edu/x', tagline: 'Harvard\'s legendary intro to CS', description: 'CS50 is Harvard University\'s introduction to computer science — the most popular CS course in the world, completely free.', difficulty: 'Beginner-Intermediate', bestFor: ['CS fundamentals', 'C, Python, SQL, JS', 'Best first CS course', 'Free Harvard certificate'], features: ['World-class lectures', 'Hands-on problem sets', 'Free certificate', 'Covers 6 languages'], tips: ['This is THE best foundational CS course — do it in Year 1', 'Do ALL problem sets, not just watch lectures', 'The certificate is genuinely respected by employers', 'David Malan is the best CS teacher on the planet'], color: 'from-red-600 to-red-700' },
];
