import { Track } from '@/types/app';

export const tracks: Track[] = [
  {
    id: 'webdev', name: 'Web Development', icon: '💻', color: 'from-blue-500 to-cyan-500',
    tagline: 'Build the modern web with cutting-edge technologies',
    difficulty: 'Beginner',
    whatYouLearn: ['HTML5 & CSS3', 'JavaScript ES6+', 'React.js', 'Node.js & Express', 'Databases (SQL & NoSQL)', 'REST APIs & Deployment'],
    roadmap: [
      { step: 1, title: 'HTML & CSS', desc: 'Learn semantic HTML, CSS Flexbox, Grid, and responsive design', link: 'https://www.w3schools.com' },
      { step: 2, title: 'JavaScript', desc: 'Master ES6+, DOM manipulation, async/await, and fetch API', link: 'https://javascript.info' },
      { step: 3, title: 'React.js', desc: 'Components, hooks, state management, and React Router', link: 'https://react.dev' },
      { step: 4, title: 'Node.js & Express', desc: 'Server-side JavaScript, REST APIs, middleware, and authentication', link: 'https://nodejs.org' },
      { step: 5, title: 'Database', desc: 'PostgreSQL/MongoDB, ORMs, and data modeling', link: 'https://www.mongodb.com/docs' },
      { step: 6, title: 'Deploy', desc: 'Git, CI/CD, Vercel/Netlify deployment, and domain setup', link: 'https://vercel.com' },
    ],
    resources: [
      { title: 'MDN Web Docs', url: 'https://developer.mozilla.org/en-US/docs/Learn', type: 'docs' },
      { title: 'freeCodeCamp', url: 'https://www.freecodecamp.org/learn/responsive-web-design', type: 'practice' },
      { title: 'Full Stack Open', url: 'https://fullstackopen.com/en', type: 'docs' },
      { title: 'Web Dev Bangla', url: 'https://www.youtube.com/results?search_query=web+development+bangla+2024', type: 'video' },
      { title: 'React Official Docs', url: 'https://react.dev', type: 'docs' },
    ],
    projects: ['Personal portfolio website', 'Blog with CMS', 'E-commerce store', 'Chat application with real-time messaging'],
    jobs: [
      { role: 'Junior Frontend Dev', bdSalary: '25-45k/mo', intlSalary: '$40-70k/yr' },
      { role: 'Full-Stack Developer', bdSalary: '45-80k/mo', intlSalary: '$60-120k/yr' },
      { role: 'React Developer', bdSalary: '40-70k/mo', intlSalary: '$70-130k/yr' },
    ],
  },
  {
    id: 'uiux', name: 'UI/UX Design', icon: '🎨', color: 'from-pink-500 to-purple-500',
    tagline: 'Design beautiful, user-centered digital experiences',
    difficulty: 'Beginner',
    whatYouLearn: ['Design Principles', 'Color Theory & Typography', 'Figma', 'Wireframing & Prototyping', 'User Research', 'Design Systems'],
    roadmap: [
      { step: 1, title: 'Design Fundamentals', desc: 'Learn layout, hierarchy, color, and typography', link: 'https://www.nngroup.com/articles' },
      { step: 2, title: 'Figma', desc: 'Master Figma for wireframing, prototyping, and collaboration', link: 'https://www.figma.com/community' },
      { step: 3, title: 'User Research', desc: 'Conduct user interviews, surveys, and usability testing' },
      { step: 4, title: 'Prototyping', desc: 'Create interactive prototypes and design systems' },
      { step: 5, title: 'Portfolio', desc: 'Build a case-study based portfolio showcasing your process' },
    ],
    resources: [
      { title: 'Figma Community', url: 'https://www.figma.com/community', type: 'practice' },
      { title: 'Nielsen Norman Group', url: 'https://www.nngroup.com/articles', type: 'docs' },
      { title: 'UI/UX Bangla', url: 'https://www.youtube.com/results?search_query=ui+ux+design+bangla+2024', type: 'video' },
      { title: 'Refactoring UI', url: 'https://www.refactoringui.com', type: 'docs' },
    ],
    projects: ['Mobile app redesign', 'Dashboard UI design', 'Design system creation', 'E-commerce UX case study'],
    jobs: [
      { role: 'UI Designer', bdSalary: '20-40k/mo', intlSalary: '$50-90k/yr' },
      { role: 'UX Researcher', bdSalary: '35-60k/mo', intlSalary: '$70-120k/yr' },
      { role: 'Product Designer', bdSalary: '50-80k/mo', intlSalary: '$80-150k/yr' },
    ],
  },
  {
    id: 'sqa', name: 'SQA & Testing', icon: '🧪', color: 'from-green-500 to-emerald-500',
    tagline: 'Ensure software quality with professional testing skills',
    difficulty: 'Beginner',
    whatYouLearn: ['Testing Fundamentals', 'Test Case Writing', 'Selenium WebDriver', 'Postman API Testing', 'Jira & Agile', 'Performance Testing'],
    roadmap: [
      { step: 1, title: 'Testing Basics', desc: 'SDLC, STLC, testing types, and test documentation', link: 'https://www.guru99.com/software-testing.html' },
      { step: 2, title: 'Manual Testing', desc: 'Test case writing, bug reporting, and test execution' },
      { step: 3, title: 'Selenium', desc: 'Web automation with Selenium WebDriver and Java/Python', link: 'https://www.selenium.dev/documentation' },
      { step: 4, title: 'API Testing', desc: 'REST API testing with Postman and automated API tests', link: 'https://learning.postman.com' },
      { step: 5, title: 'CI/CD & Agile', desc: 'Jira, Scrum, and integrating tests into CI/CD pipelines' },
      { step: 6, title: 'Performance Testing', desc: 'JMeter and load testing for scalability' },
    ],
    resources: [
      { title: 'Guru99 Testing', url: 'https://www.guru99.com/software-testing.html', type: 'docs' },
      { title: 'Selenium Docs', url: 'https://www.selenium.dev/documentation', type: 'docs' },
      { title: 'SQA Bangla', url: 'https://www.youtube.com/results?search_query=sqa+software+testing+career+bangla', type: 'video' },
      { title: 'ISTQB', url: 'https://www.istqb.org', type: 'docs' },
    ],
    projects: ['Test plan for web app', 'Selenium automation suite', 'API test collection in Postman', 'Performance test report'],
    jobs: [
      { role: 'SQA Engineer', bdSalary: '25-45k/mo', intlSalary: '$50-80k/yr' },
      { role: 'Automation Tester', bdSalary: '40-70k/mo', intlSalary: '$70-110k/yr' },
      { role: 'QA Lead', bdSalary: '60-100k/mo', intlSalary: '$90-140k/yr' },
    ],
  },
  {
    id: 'web3', name: 'Web3 & Blockchain', icon: '🔗', color: 'from-yellow-500 to-orange-500',
    tagline: 'Build decentralized applications on the blockchain',
    difficulty: 'Advanced',
    whatYouLearn: ['Blockchain Basics', 'Ethereum & EVM', 'Solidity', 'Smart Contracts', 'DeFi & NFTs', 'dApp Development'],
    roadmap: [
      { step: 1, title: 'Blockchain Basics', desc: 'Understand distributed ledger, consensus, and cryptography', link: 'https://ethereum.org/en/developers/docs' },
      { step: 2, title: 'Solidity', desc: 'Learn Solidity for smart contract development', link: 'https://docs.soliditylang.org' },
      { step: 3, title: 'Smart Contracts', desc: 'Write, test, and deploy smart contracts with Hardhat' },
      { step: 4, title: 'DeFi & NFTs', desc: 'Build DeFi protocols and NFT marketplaces' },
      { step: 5, title: 'dApp', desc: 'Build a full decentralized application with React + ethers.js' },
    ],
    resources: [
      { title: 'Ethereum Docs', url: 'https://ethereum.org/en/developers/docs', type: 'docs' },
      { title: 'CryptoZombies', url: 'https://cryptozombies.io', type: 'practice' },
      { title: 'Web3 Bangla', url: 'https://www.youtube.com/results?search_query=web3+blockchain+bangla', type: 'video' },
      { title: 'Alchemy University', url: 'https://www.alchemy.com/university', type: 'practice' },
    ],
    projects: ['ERC-20 token', 'NFT minting dApp', 'Decentralized voting system', 'DeFi yield aggregator'],
    jobs: [
      { role: 'Blockchain Developer', bdSalary: '50-90k/mo', intlSalary: '$80-150k/yr' },
      { role: 'Smart Contract Auditor', bdSalary: '60-100k/mo', intlSalary: '$100-200k/yr' },
    ],
  },
  {
    id: 'aiml', name: 'AI & Machine Learning', icon: '🤖', color: 'from-purple-500 to-violet-500',
    tagline: 'Build intelligent systems that learn and adapt',
    difficulty: 'Advanced',
    whatYouLearn: ['Python & NumPy/Pandas', 'Data Visualization', 'ML Algorithms', 'Deep Learning', 'NLP', 'Computer Vision'],
    roadmap: [
      { step: 1, title: 'Python', desc: 'Master Python with NumPy, Pandas, Matplotlib', link: 'https://www.kaggle.com/learn/python' },
      { step: 2, title: 'Data Analysis', desc: 'Data cleaning, EDA, and visualization with Seaborn' },
      { step: 3, title: 'ML Algorithms', desc: 'Regression, classification, clustering with scikit-learn', link: 'https://www.kaggle.com/learn' },
      { step: 4, title: 'Deep Learning', desc: 'Neural networks, CNNs, RNNs with TensorFlow/PyTorch', link: 'https://www.fast.ai' },
      { step: 5, title: 'Specialization', desc: 'Choose NLP, Computer Vision, or Reinforcement Learning' },
      { step: 6, title: 'Deploy', desc: 'Model deployment with Flask/FastAPI and cloud services' },
    ],
    resources: [
      { title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', type: 'practice' },
      { title: 'Fast.ai', url: 'https://www.fast.ai', type: 'docs' },
      { title: 'ML Bangla', url: 'https://www.youtube.com/results?search_query=machine+learning+python+bangla+2024', type: 'video' },
      { title: 'TensorFlow Tutorials', url: 'https://www.tensorflow.org/tutorials', type: 'docs' },
      { title: 'PyTorch Tutorials', url: 'https://pytorch.org/tutorials', type: 'docs' },
    ],
    projects: ['House price predictor', 'Image classifier', 'Sentiment analysis tool', 'Chatbot with NLP'],
    jobs: [
      { role: 'ML Engineer', bdSalary: '50-80k/mo', intlSalary: '$90-160k/yr' },
      { role: 'Data Scientist', bdSalary: '45-75k/mo', intlSalary: '$80-140k/yr' },
      { role: 'AI Researcher', bdSalary: '60-100k/mo', intlSalary: '$100-180k/yr' },
    ],
  },
  {
    id: 'cyber', name: 'Cybersecurity', icon: '🛡️', color: 'from-red-500 to-rose-500',
    tagline: 'Protect systems and data from cyber threats',
    difficulty: 'Intermediate',
    whatYouLearn: ['Networking & Linux', 'Python Scripting', 'OWASP Top 10', 'Ethical Hacking', 'CTF Competitions', 'Penetration Testing'],
    roadmap: [
      { step: 1, title: 'Networking & Linux', desc: 'TCP/IP, Linux commands, and system administration' },
      { step: 2, title: 'Python Scripting', desc: 'Write security tools and automation scripts' },
      { step: 3, title: 'Web Security', desc: 'OWASP Top 10, XSS, SQL injection, CSRF', link: 'https://owasp.org' },
      { step: 4, title: 'Ethical Hacking', desc: 'Reconnaissance, scanning, exploitation with Kali Linux', link: 'https://tryhackme.com' },
      { step: 5, title: 'CTF & Bug Bounty', desc: 'Participate in CTF competitions and bug bounty programs', link: 'https://www.hackthebox.com' },
    ],
    resources: [
      { title: 'TryHackMe', url: 'https://tryhackme.com', type: 'practice' },
      { title: 'HackTheBox', url: 'https://www.hackthebox.com', type: 'practice' },
      { title: 'Cyber Bangla', url: 'https://www.youtube.com/results?search_query=ethical+hacking+cybersecurity+bangla', type: 'video' },
      { title: 'Cybrary', url: 'https://www.cybrary.it', type: 'docs' },
    ],
    projects: ['Network scanner in Python', 'Vulnerability assessment report', 'CTF writeups portfolio', 'Web app security audit'],
    jobs: [
      { role: 'Security Analyst', bdSalary: '40-70k/mo', intlSalary: '$70-120k/yr' },
      { role: 'Penetration Tester', bdSalary: '50-90k/mo', intlSalary: '$80-150k/yr' },
      { role: 'Security Engineer', bdSalary: '60-100k/mo', intlSalary: '$90-160k/yr' },
    ],
  },
  {
    id: 'cloud', name: 'Cloud & DevOps', icon: '☁️', color: 'from-sky-500 to-blue-600',
    tagline: 'Master cloud infrastructure and DevOps practices',
    difficulty: 'Intermediate',
    whatYouLearn: ['Linux & Git', 'Docker & Containers', 'CI/CD Pipelines', 'Kubernetes', 'AWS/GCP/Azure', 'Infrastructure as Code'],
    roadmap: [
      { step: 1, title: 'Linux & Git', desc: 'Linux system admin and Git version control', link: 'https://www.docker.com/get-started' },
      { step: 2, title: 'Docker', desc: 'Containerization, Docker Compose, and image management' },
      { step: 3, title: 'CI/CD', desc: 'GitHub Actions, Jenkins, and automated deployment pipelines' },
      { step: 4, title: 'Kubernetes', desc: 'Container orchestration, pods, services, and deployments', link: 'https://kubernetes.io/docs/tutorials' },
      { step: 5, title: 'AWS', desc: 'EC2, S3, Lambda, RDS, and cloud architecture', link: 'https://aws.amazon.com/training/free' },
      { step: 6, title: 'Terraform', desc: 'Infrastructure as Code and cloud automation' },
    ],
    resources: [
      { title: 'AWS Free Training', url: 'https://aws.amazon.com/training/free', type: 'practice' },
      { title: 'Docker Docs', url: 'https://www.docker.com/get-started', type: 'docs' },
      { title: 'Cloud Bangla', url: 'https://www.youtube.com/results?search_query=aws+cloud+devops+bangla', type: 'video' },
      { title: 'Kubernetes Docs', url: 'https://kubernetes.io/docs/tutorials', type: 'docs' },
    ],
    projects: ['Dockerize a web app', 'CI/CD pipeline with GitHub Actions', 'Deploy on AWS EC2', 'Kubernetes cluster setup'],
    jobs: [
      { role: 'DevOps Engineer', bdSalary: '50-90k/mo', intlSalary: '$80-150k/yr' },
      { role: 'Cloud Architect', bdSalary: '70-120k/mo', intlSalary: '$100-180k/yr' },
      { role: 'SRE', bdSalary: '60-100k/mo', intlSalary: '$90-170k/yr' },
    ],
  },
  {
    id: 'mobile', name: 'Mobile Development', icon: '📱', color: 'from-teal-500 to-green-500',
    tagline: 'Build native and cross-platform mobile apps',
    difficulty: 'Intermediate',
    whatYouLearn: ['Dart & Flutter', 'React Native', 'UI Components', 'State Management', 'Firebase', 'App Store Publishing'],
    roadmap: [
      { step: 1, title: 'Choose Framework', desc: 'Flutter (Dart) or React Native (JavaScript)', link: 'https://flutter.dev/docs' },
      { step: 2, title: 'UI Development', desc: 'Build beautiful UI with widgets/components' },
      { step: 3, title: 'Navigation', desc: 'Screen navigation and routing patterns' },
      { step: 4, title: 'State Management', desc: 'Provider/Riverpod (Flutter) or Redux/Context (RN)' },
      { step: 5, title: 'Backend', desc: 'Firebase/Supabase for auth, database, and storage', link: 'https://firebase.google.com' },
      { step: 6, title: 'Publish', desc: 'App signing, store listing, and deployment' },
    ],
    resources: [
      { title: 'Flutter Docs', url: 'https://flutter.dev/docs', type: 'docs' },
      { title: 'Flutter Bangla', url: 'https://www.youtube.com/results?search_query=flutter+bangla+tutorial+2024', type: 'video' },
      { title: 'React Native Docs', url: 'https://reactnative.dev/docs/getting-started', type: 'docs' },
      { title: 'Dart Guide', url: 'https://dart.dev/guides', type: 'docs' },
    ],
    projects: ['Todo app with persistence', 'Weather app with API', 'Social media feed clone', 'E-commerce mobile app'],
    jobs: [
      { role: 'Flutter Developer', bdSalary: '35-65k/mo', intlSalary: '$60-110k/yr' },
      { role: 'Mobile Developer', bdSalary: '40-75k/mo', intlSalary: '$70-130k/yr' },
      { role: 'React Native Dev', bdSalary: '40-70k/mo', intlSalary: '$65-120k/yr' },
    ],
  },
  {
    id: 'cp', name: 'Competitive Programming', icon: '🏆', color: 'from-amber-500 to-yellow-500',
    tagline: 'Solve algorithmic challenges and compete globally',
    difficulty: 'Advanced',
    whatYouLearn: ['C++ STL', 'Time Complexity', 'Mathematics', 'Dynamic Programming', 'Graph Theory', 'Advanced Data Structures'],
    roadmap: [
      { step: 1, title: 'C++ & STL', desc: 'Master C++ with vectors, maps, sets, and algorithms', link: 'https://cses.fi/problemset' },
      { step: 2, title: 'Math & Greedy', desc: 'Number theory, modular arithmetic, and greedy strategies' },
      { step: 3, title: 'Binary Search', desc: 'Binary search on answer, two pointers technique' },
      { step: 4, title: 'Dynamic Programming', desc: 'Knapsack, LCS, LIS, DP on trees and grids' },
      { step: 5, title: 'Graph Theory', desc: 'BFS, DFS, shortest paths, MST, and network flow' },
      { step: 6, title: 'Advanced', desc: 'Segment trees, Fenwick trees, string algorithms, and geometry' },
    ],
    resources: [
      { title: 'Codeforces', url: 'https://codeforces.com', type: 'practice' },
      { title: 'CSES Problem Set', url: 'https://cses.fi/problemset', type: 'practice' },
      { title: 'USACO Guide', url: 'https://usaco.guide', type: 'docs' },
      { title: 'CP Algorithms', url: 'https://cp-algorithms.com', type: 'docs' },
      { title: 'CP Bangla', url: 'https://www.youtube.com/results?search_query=competitive+programming+codeforces+bangla', type: 'video' },
    ],
    projects: ['Solve 200+ Codeforces problems', 'Reach Specialist (1400+) rating', 'ICPC team practice', 'Write problem editorials blog'],
    jobs: [
      { role: 'Software Engineer (FAANG)', bdSalary: '80-150k/mo', intlSalary: '$120-200k/yr' },
      { role: 'Algorithm Engineer', bdSalary: '60-100k/mo', intlSalary: '$100-170k/yr' },
    ],
  },
];
